name: Build and test ruby-versions-action

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
    branches:
      - "main"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        name: Build
        with:
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ruby-versions-action
      - run: docker run ruby-versions-action
        name: Run container once
